/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ca.ulaval.glo2004.gui;

import ca.ulaval.glo2004.domaine.Controleur;
import java.awt.Color;

public class fenetreProprietes extends javax.swing.JPanel {

    /**
     * Creates new form fenetreProprietes
     */
    public fenetreProprietes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PositionX = new javax.swing.JLabel();
        positionXPiEntree = new javax.swing.JTextField();
        positionXFtLabel = new javax.swing.JLabel();
        positionXPoEntree = new javax.swing.JTextField();
        positionXPoNum = new javax.swing.JTextField();
        longueurAvantDivision1 = new javax.swing.JLabel();
        positionXPoDen = new javax.swing.JTextField();
        longueurAvantInLabel1 = new javax.swing.JLabel();
        longueurAvantLabel1 = new javax.swing.JLabel();
        hauteurPiEntree = new javax.swing.JTextField();
        longueurAvantFtLabel1 = new javax.swing.JLabel();
        hauteurPoEntree = new javax.swing.JTextField();
        hauteurPoNum = new javax.swing.JTextField();
        longueurAvantDivision2 = new javax.swing.JLabel();
        hauteurPoDen = new javax.swing.JTextField();
        longueurAvantInLabel2 = new javax.swing.JLabel();
        longueurAvantLabel2 = new javax.swing.JLabel();
        largeurPiEntree = new javax.swing.JTextField();
        longueurAvantFtLabel2 = new javax.swing.JLabel();
        largeurPoEntree = new javax.swing.JTextField();
        largeurPoNum = new javax.swing.JTextField();
        longueurAvantDivision3 = new javax.swing.JLabel();
        largeurPoDen = new javax.swing.JTextField();
        longueurAvantInLabel3 = new javax.swing.JLabel();
        PositionX2 = new javax.swing.JLabel();
        positionYPiEntree = new javax.swing.JTextField();
        positionXFtLabel2 = new javax.swing.JLabel();
        positionYPoEntree = new javax.swing.JTextField();
        positionYPoNum = new javax.swing.JTextField();
        longueurAvantDivision4 = new javax.swing.JLabel();
        positionYPoDen = new javax.swing.JTextField();
        longueurAvantInLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        accessoireCompteur = new javax.swing.JLabel();
        sauvegarderAccessoire = new javax.swing.JButton();
        effacerAccessoire1 = new javax.swing.JButton();
        indicateurModification = new javax.swing.JLabel();
        vieuxPosX = new javax.swing.JLabel();
        vieuxPosY = new javax.swing.JLabel();

        setName(""); // NOI18N

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 251));

        PositionX.setForeground(new java.awt.Color(255, 255, 255));
        PositionX.setText("Position X :");

        positionXPiEntree.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                positionXPiEntreeFocusLost(evt);
            }
        });
        positionXPiEntree.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                positionXPiEntreeInputMethodTextChanged(evt);
            }
        });

        positionXFtLabel.setForeground(new java.awt.Color(255, 255, 255));
        positionXFtLabel.setText("ft");

        longueurAvantDivision1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        longueurAvantDivision1.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantDivision1.setText("/");

        longueurAvantInLabel1.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantInLabel1.setText("in");

        longueurAvantLabel1.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantLabel1.setText("Hauteur :");

        longueurAvantFtLabel1.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantFtLabel1.setText("ft");

        longueurAvantDivision2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        longueurAvantDivision2.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantDivision2.setText("/");

        longueurAvantInLabel2.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantInLabel2.setText("in");

        longueurAvantLabel2.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantLabel2.setText("Largeur :");

        longueurAvantFtLabel2.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantFtLabel2.setText("ft");

        longueurAvantDivision3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        longueurAvantDivision3.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantDivision3.setText("/");

        longueurAvantInLabel3.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantInLabel3.setText("in");

        PositionX2.setForeground(new java.awt.Color(255, 255, 255));
        PositionX2.setText("Position Y :");

        positionYPiEntree.setMaximumSize(new java.awt.Dimension(64, 22));

        positionXFtLabel2.setForeground(new java.awt.Color(255, 255, 255));
        positionXFtLabel2.setText("ft");

        longueurAvantDivision4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        longueurAvantDivision4.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantDivision4.setText("/");

        longueurAvantInLabel4.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantInLabel4.setText("in");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fenêtre");

        accessoireCompteur.setForeground(new java.awt.Color(255, 255, 255));
        accessoireCompteur.setText("X");

        sauvegarderAccessoire.setText("Sauvegarder");
        sauvegarderAccessoire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauvegarderAccessoireActionPerformed(evt);
            }
        });

        effacerAccessoire1.setText("Effacer");
        effacerAccessoire1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                effacerAccessoire1ActionPerformed(evt);
            }
        });

        indicateurModification.setForeground(new java.awt.Color(51, 255, 51));
        indicateurModification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        indicateurModification.setText("Sauvegardé");

        vieuxPosX.setEnabled(false);

        vieuxPosY.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(accessoireCompteur, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PositionX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(positionXPiEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(positionXFtLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(positionXPoEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(positionXPoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(longueurAvantDivision1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(positionXPoDen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(longueurAvantInLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(PositionX2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(positionYPiEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(positionXFtLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(positionYPoEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(positionYPoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(longueurAvantDivision4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(positionYPoDen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(longueurAvantLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(largeurPiEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(longueurAvantFtLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(largeurPoEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(largeurPoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(longueurAvantDivision3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(largeurPoDen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(longueurAvantLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hauteurPiEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(longueurAvantFtLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hauteurPoEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hauteurPoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(longueurAvantDivision2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hauteurPoDen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(longueurAvantInLabel3)
                                    .addComponent(longueurAvantInLabel2)
                                    .addComponent(longueurAvantInLabel4))))
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sauvegarderAccessoire, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(indicateurModification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(vieuxPosX)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(effacerAccessoire1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vieuxPosY))
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(accessoireCompteur))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(longueurAvantDivision1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(PositionX)
                                        .addComponent(positionXPiEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(positionXFtLabel)
                                        .addComponent(positionXPoEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(positionXPoNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(positionXPoDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(longueurAvantInLabel1)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(longueurAvantDivision4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(PositionX2)
                                        .addComponent(positionYPiEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(positionXFtLabel2)
                                        .addComponent(positionYPoEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(positionYPoNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(positionYPoDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(longueurAvantInLabel4)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hauteurPoDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(longueurAvantInLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(longueurAvantLabel1)
                                    .addComponent(hauteurPiEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(longueurAvantFtLabel1)
                                    .addComponent(hauteurPoEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hauteurPoNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(longueurAvantDivision2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(longueurAvantDivision3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(longueurAvantLabel2)
                                        .addComponent(largeurPiEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(longueurAvantFtLabel2)
                                        .addComponent(largeurPoEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(largeurPoNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(largeurPoDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(longueurAvantInLabel3)))))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sauvegarderAccessoire, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(effacerAccessoire1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(indicateurModification))
                        .addGap(18, 18, 18)
                        .addComponent(vieuxPosX)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(vieuxPosY)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sauvegarderAccessoireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauvegarderAccessoireActionPerformed
        try{
        int accessoireCompteurVar = Integer.parseInt(accessoireCompteur.getText());
        
       
        float[] posX = {Float.valueOf(positionXPiEntree.getText()),
        Float.valueOf(positionXPoEntree.getText()), Float.valueOf(positionXPoNum.getText()),
        Float.valueOf(positionXPoDen.getText())};
        
        float[] hauteur = {Float.valueOf(hauteurPiEntree.getText()),
        Float.valueOf(hauteurPoEntree.getText()), Float.valueOf(hauteurPoNum.getText()),
        Float.valueOf(hauteurPoDen.getText())};
        
        float[] largeur = {Float.valueOf(largeurPiEntree.getText()), Float.valueOf(largeurPoEntree.getText()),
        Float.valueOf(largeurPoNum.getText()), Float.valueOf(largeurPoDen.getText())};
        
        float[] posY = {Float.valueOf(positionYPiEntree.getText()),
        Float.valueOf(positionYPoEntree.getText()), Float.valueOf(positionYPoNum.getText()),
        Float.valueOf(positionYPoDen.getText())};
        
        if (posX[3]==0.0f)
        {
            positionXPoDen.setText("1");
            ErreurFenetre erreur = new ErreurFenetre();
            erreur.setBounds(1500, 720, 300, 200);
            erreur.setMsg("Division par 0 remplacée");
            erreur.setVisible(true);
        }
        if (hauteur[3]==0.0f)
        {
            hauteurPoDen.setText("1");
            ErreurFenetre erreur = new ErreurFenetre();
            erreur.setBounds(1500, 720, 300, 200);
            erreur.setMsg("Division par 0 remplacée");
            erreur.setVisible(true);
        }
        if (largeur[3]==0.0f)
        {
            largeurPoDen.setText("1");
            ErreurFenetre erreur = new ErreurFenetre();
            erreur.setBounds(1500, 720, 300, 200);
            erreur.setMsg("Division par 0 remplacée");
            erreur.setVisible(true);
        }
        if (posY[3]==0.0f)
        {
            positionYPoDen.setText("1");
            ErreurFenetre erreur = new ErreurFenetre();
            erreur.setBounds(1500, 720, 300, 200);
            erreur.setMsg("Division par 0 remplacée");
            erreur.setVisible(true);
        }
        if ((posX[0]<0.0f)||(posX[1]<0.0f)||(posX[2]<0.0f)||(posX[3]<0.0f)||
                (hauteur[0]<0.0f)||(hauteur[1]<0.0f)||(hauteur[2]<0.0f)||(hauteur[3]<0.0f)||
                (largeur[0]<0.0f)||(largeur[1]<0.0f)||(largeur[2]<0.0f)||(largeur[3]<0.0f)
                ||(posY[0]<0.0f)||(posY[1]<0.0f)||(posY[2]<0.0f)||(posY[3]<0.0f))
        {
            ErreurFenetre erreur = new ErreurFenetre();
            erreur.setMsg("Nombre négatif invalide");
            erreur.setBounds(1500, 720, 300, 200);
            erreur.setVisible(true);
        }
        else{
        if (Controleur.modifierDimensionAcc(hauteur[0]*12.0f + hauteur[1] + hauteur[2]/Float.valueOf(hauteurPoDen.getText()),
                largeur[0]*12+largeur[1]+largeur[2]/Float.valueOf(largeurPoDen.getText()),
                posX[0]*12+posX[1]+posX[2]/Float.valueOf(positionXPoDen.getText()),
                posY[0]*12 + posY[1] + posY[2]/Float.valueOf(positionYPoDen.getText()), accessoireCompteurVar,true, false)){
        }
        
        }
        }
        catch (NumberFormatException a)
        {
            ErreurFenetre erreur = new ErreurFenetre();
            erreur.setMsg("Caractère non numerique ou vide");
            erreur.setVisible(true);
            erreur.setBounds(1500, 720, 300, 200);
        }       
        //À changer livrable 4
    }//GEN-LAST:event_sauvegarderAccessoireActionPerformed

    private void effacerAccessoire1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_effacerAccessoire1ActionPerformed
        int accessoireCompteurVar = Integer.parseInt(accessoireCompteur.getText());
        if (Controleur.supprimerAccessoire(accessoireCompteurVar)){
        getParent().remove(fenetreProprietes.this);
        }
    }//GEN-LAST:event_effacerAccessoire1ActionPerformed

    private void positionXPiEntreeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_positionXPiEntreeInputMethodTextChanged
        indicateurModification.setForeground(Color.blue);
        indicateurModification.setText("Modifié");
    }//GEN-LAST:event_positionXPiEntreeInputMethodTextChanged

    private void positionXPiEntreeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_positionXPiEntreeFocusLost
        indicateurModification.setForeground(Color.blue);
        indicateurModification.setText("Modifié");
    }//GEN-LAST:event_positionXPiEntreeFocusLost

    public void initialisation (float[] posX, float[] posY, float[] hauteur, float[] largeur, int cle, Controleur ControleurArg) {
        //On utilise des array pour alleger la definition et le nombre de variables
        //On initialise tout les champs aux valeurs passées dans la case de création
        positionXPiEntree.setText(String.valueOf(posX[0]));
        positionXPoEntree.setText(String.valueOf(posX[1]));
        positionXPoNum.setText(String.valueOf(posX[2]));
        positionXPoDen.setText(String.valueOf(posX[3]));
        positionYPiEntree.setText(String.valueOf(posY[0]));
        positionYPoEntree.setText(String.valueOf(posY[1]));
        positionYPoNum.setText(String.valueOf(posY[2]));
        positionYPoDen.setText(String.valueOf(posY[3]));
        hauteurPiEntree.setText(String.valueOf(hauteur[0]));
        hauteurPoEntree.setText(String.valueOf(hauteur[1]));
        hauteurPoNum.setText(String.valueOf(hauteur[2]));
        hauteurPoDen.setText(String.valueOf(hauteur[3]));
        largeurPiEntree.setText(String.valueOf(largeur[0]));
        largeurPoEntree.setText(String.valueOf(largeur[1]));
        largeurPoNum.setText(String.valueOf(largeur[2]));
        largeurPoDen.setText(String.valueOf(largeur[3]));
        accessoireCompteur.setText(String.valueOf(cle));
        Controleur = ControleurArg;
        
    }

    private Controleur Controleur;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PositionX;
    private javax.swing.JLabel PositionX2;
    private javax.swing.JLabel accessoireCompteur;
    private javax.swing.JButton effacerAccessoire1;
    private javax.swing.JTextField hauteurPiEntree;
    private javax.swing.JTextField hauteurPoDen;
    private javax.swing.JTextField hauteurPoEntree;
    private javax.swing.JTextField hauteurPoNum;
    private javax.swing.JLabel indicateurModification;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField largeurPiEntree;
    private javax.swing.JTextField largeurPoDen;
    private javax.swing.JTextField largeurPoEntree;
    private javax.swing.JTextField largeurPoNum;
    private javax.swing.JLabel longueurAvantDivision1;
    private javax.swing.JLabel longueurAvantDivision2;
    private javax.swing.JLabel longueurAvantDivision3;
    private javax.swing.JLabel longueurAvantDivision4;
    private javax.swing.JLabel longueurAvantFtLabel1;
    private javax.swing.JLabel longueurAvantFtLabel2;
    private javax.swing.JLabel longueurAvantInLabel1;
    private javax.swing.JLabel longueurAvantInLabel2;
    private javax.swing.JLabel longueurAvantInLabel3;
    private javax.swing.JLabel longueurAvantInLabel4;
    private javax.swing.JLabel longueurAvantLabel1;
    private javax.swing.JLabel longueurAvantLabel2;
    private javax.swing.JLabel positionXFtLabel;
    private javax.swing.JLabel positionXFtLabel2;
    private javax.swing.JTextField positionXPiEntree;
    private javax.swing.JTextField positionXPoDen;
    private javax.swing.JTextField positionXPoEntree;
    private javax.swing.JTextField positionXPoNum;
    private javax.swing.JTextField positionYPiEntree;
    private javax.swing.JTextField positionYPoDen;
    private javax.swing.JTextField positionYPoEntree;
    private javax.swing.JTextField positionYPoNum;
    private javax.swing.JButton sauvegarderAccessoire;
    private javax.swing.JLabel vieuxPosX;
    private javax.swing.JLabel vieuxPosY;
    // End of variables declaration//GEN-END:variables
}
