/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ca.ulaval.glo2004.gui;

import ca.ulaval.glo2004.domaine.Controleur;
import java.awt.Color;

public class porteProprietes extends javax.swing.JPanel {

    /**
     * Creates new form porteProprietes
     */
    public porteProprietes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PositionX = new javax.swing.JLabel();
        positionXPiEntree = new javax.swing.JTextField();
        positionXFtLabel = new javax.swing.JLabel();
        positionXPoEntree = new javax.swing.JTextField();
        positionXPoNum = new javax.swing.JTextField();
        longueurAvantDivision = new javax.swing.JLabel();
        positionXPoDen = new javax.swing.JTextField();
        longueurAvantInLabel = new javax.swing.JLabel();
        longueurAvantLabel1 = new javax.swing.JLabel();
        hauteurPiEntree = new javax.swing.JTextField();
        longueurAvantFtLabel1 = new javax.swing.JLabel();
        hauteurPoEntree = new javax.swing.JTextField();
        hauteurPoNum = new javax.swing.JTextField();
        longueurAvantDivision1 = new javax.swing.JLabel();
        hauteurPoDen = new javax.swing.JTextField();
        longueurAvantInLabel1 = new javax.swing.JLabel();
        longueurAvantLabel2 = new javax.swing.JLabel();
        largeurPiEntree = new javax.swing.JTextField();
        longueurAvantFtLabel2 = new javax.swing.JLabel();
        largeurPoEntree = new javax.swing.JTextField();
        largeurPoNum = new javax.swing.JTextField();
        longueurAvantDivision2 = new javax.swing.JLabel();
        largeurPoDen = new javax.swing.JTextField();
        longueurAvantInLabel2 = new javax.swing.JLabel();
        sauvegarderAccessoire = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dicoCle = new javax.swing.JLabel();
        effacerAccessoire1 = new javax.swing.JButton();
        indicateurModification = new javax.swing.JLabel();
        vieuxValX = new javax.swing.JLabel();
        vieuxValY = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(350, 219));

        PositionX.setForeground(new java.awt.Color(255, 255, 255));
        PositionX.setText("Position X :");

        positionXPiEntree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                positionXPiEntreeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                positionXPiEntreeMouseExited(evt);
            }
        });
        positionXPiEntree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                positionXPiEntreeKeyTyped(evt);
            }
        });

        positionXFtLabel.setForeground(new java.awt.Color(255, 255, 255));
        positionXFtLabel.setText("ft");

        positionXPoEntree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                positionXPoEntreeMouseClicked(evt);
            }
        });
        positionXPoEntree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                positionXPoEntreeKeyTyped(evt);
            }
        });

        longueurAvantDivision.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        longueurAvantDivision.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantDivision.setText("/");

        longueurAvantInLabel.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantInLabel.setText("in");

        longueurAvantLabel1.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantLabel1.setText("Hauteur :");

        hauteurPiEntree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hauteurPiEntreeMouseClicked(evt);
            }
        });
        hauteurPiEntree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hauteurPiEntreeKeyTyped(evt);
            }
        });

        longueurAvantFtLabel1.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantFtLabel1.setText("ft");

        hauteurPoEntree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hauteurPoEntreeMouseClicked(evt);
            }
        });
        hauteurPoEntree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hauteurPoEntreeKeyTyped(evt);
            }
        });

        longueurAvantDivision1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        longueurAvantDivision1.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantDivision1.setText("/");

        longueurAvantInLabel1.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantInLabel1.setText("in");

        longueurAvantLabel2.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantLabel2.setText("Largeur :");

        largeurPiEntree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                largeurPiEntreeMouseClicked(evt);
            }
        });
        largeurPiEntree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                largeurPiEntreeKeyTyped(evt);
            }
        });

        longueurAvantFtLabel2.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantFtLabel2.setText("ft");

        largeurPoEntree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                largeurPoEntreeMouseClicked(evt);
            }
        });
        largeurPoEntree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                largeurPoEntreeKeyTyped(evt);
            }
        });

        longueurAvantDivision2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        longueurAvantDivision2.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantDivision2.setText("/");

        longueurAvantInLabel2.setForeground(new java.awt.Color(255, 255, 255));
        longueurAvantInLabel2.setText("in");

        sauvegarderAccessoire.setText("Sauvegarder");
        sauvegarderAccessoire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauvegarderAccessoireActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Porte");

        dicoCle.setForeground(new java.awt.Color(255, 255, 255));
        dicoCle.setText("X");

        effacerAccessoire1.setText("Effacer");
        effacerAccessoire1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                effacerAccessoire1ActionPerformed(evt);
            }
        });

        indicateurModification.setForeground(new java.awt.Color(0, 255, 0));
        indicateurModification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        indicateurModification.setText("Modifié");
        indicateurModification.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        vieuxValX.setEnabled(false);

        vieuxValY.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 38, Short.MAX_VALUE)
                        .addComponent(longueurAvantLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(largeurPiEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(longueurAvantFtLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(largeurPoEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(largeurPoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(longueurAvantDivision2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(largeurPoDen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(longueurAvantInLabel2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(longueurAvantLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hauteurPiEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(longueurAvantFtLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hauteurPoEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hauteurPoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(longueurAvantDivision1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hauteurPoDen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(longueurAvantInLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dicoCle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PositionX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(positionXPiEntree)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(positionXFtLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(positionXPoEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(positionXPoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(longueurAvantDivision)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(positionXPoDen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(longueurAvantInLabel)))
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sauvegarderAccessoire, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(indicateurModification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(vieuxValX)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(effacerAccessoire1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vieuxValY))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dicoCle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(longueurAvantDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(PositionX)
                                .addComponent(positionXPiEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(positionXFtLabel)
                                .addComponent(positionXPoEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(positionXPoNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(positionXPoDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(longueurAvantInLabel)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(longueurAvantDivision1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(longueurAvantLabel1)
                                .addComponent(hauteurPiEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(longueurAvantFtLabel1)
                                .addComponent(hauteurPoEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hauteurPoNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(hauteurPoDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(longueurAvantInLabel1)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(longueurAvantDivision2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(longueurAvantLabel2)
                                .addComponent(largeurPiEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(longueurAvantFtLabel2)
                                .addComponent(largeurPoEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(largeurPoNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(largeurPoDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(longueurAvantInLabel2)))))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sauvegarderAccessoire, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(effacerAccessoire1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indicateurModification))
                .addGap(12, 12, 12)
                .addComponent(vieuxValY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vieuxValX)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sauvegarderAccessoireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauvegarderAccessoireActionPerformed
        try{
        float[] posX = {Float.valueOf(positionXPiEntree.getText()),
        Float.valueOf(positionXPoEntree.getText()), Float.valueOf(positionXPoNum.getText()),
        Float.valueOf(positionXPoDen.getText())};
        
        float[] hauteur = {Float.valueOf(hauteurPiEntree.getText()),
        Float.valueOf(hauteurPoEntree.getText()), Float.valueOf(hauteurPoNum.getText()),
        Float.valueOf(hauteurPoDen.getText())};
        
        float[] largeur = {Float.valueOf(largeurPiEntree.getText()), Float.valueOf(largeurPoEntree.getText()),
        Float.valueOf(largeurPoNum.getText()), Float.valueOf(largeurPoDen.getText())};
        if (posX[3]==0.0f)
        {
            positionXPoDen.setText("1");
            ErreurFenetre erreur = new ErreurFenetre();
            erreur.setBounds(1500, 720, 300, 200);
            erreur.setMsg("Division par 0 remplacée");
            erreur.setVisible(true);
        }
        if (hauteur[3]==0.0f)
        {
            hauteurPoDen.setText("1");
            ErreurFenetre erreur = new ErreurFenetre();
            erreur.setBounds(1500, 720, 300, 200);
            erreur.setMsg("Division par 0 remplacée");
            erreur.setVisible(true);
        }
        if (largeur[3]==0.0f)
        {
            largeurPoDen.setText("1");
            ErreurFenetre erreur = new ErreurFenetre();
            erreur.setBounds(1500, 720, 300, 200);
            erreur.setMsg("Division par 0 remplacée");
            erreur.setVisible(true);
        }
        if ((posX[0]<0.0f)||(posX[1]<0.0f)||(posX[2]<0.0f)||(posX[3]<0.0f)||
                (hauteur[0]<0.0f)||(hauteur[1]<0.0f)||(hauteur[2]<0.0f)||(hauteur[3]<0.0f)||
                (largeur[0]<0.0f)||(largeur[1]<0.0f)||(largeur[2]<0.0f)||(largeur[3]<0.0f))
        {
            ErreurFenetre erreur = new ErreurFenetre();
            erreur.setMsg("Nombre négatif invalide");
            erreur.setBounds(1500, 720, 300, 200);
            erreur.setVisible(true);
        }
        float positionXFtEntreeVar = Float.valueOf(positionXPiEntree.getText());
        float positionXInEntreeVar = Float.valueOf(positionXPoEntree.getText());
        float positionXInNumVar = Float.valueOf(positionXPoNum.getText());
        float positionXInDenVar = Float.valueOf(positionXPoDen.getText());
        float longueurFtEntreeVar = Float.valueOf(hauteurPiEntree.getText());
        float longueurInVar = Float.valueOf(hauteurPoEntree.getText());
        float longueurInNumVar = Float.valueOf(hauteurPoNum.getText());
        float longueurInDenVar = Float.valueOf(hauteurPoDen.getText());
        float largeurFtVar = Float.valueOf(largeurPiEntree.getText());
        float largeurInVar = Float.valueOf(largeurPoEntree.getText());
        float largeurInNumVar = Float.valueOf(largeurPoNum.getText());
        float largeurInDenVar = Float.valueOf(largeurPoDen.getText());
        int dicoCleVar = Integer.parseInt(dicoCle.getText());
        Controleur.modifierDimensionAcc( 
                                        12.0f*longueurFtEntreeVar + longueurInVar + longueurInNumVar/longueurInDenVar,
                12*largeurFtVar + largeurInVar + largeurInNumVar/largeurInDenVar,
                positionXFtEntreeVar*12.0f + positionXInEntreeVar + positionXInNumVar/positionXInDenVar, 6.0f*longueurFtEntreeVar + longueurInVar + longueurInNumVar/longueurInDenVar, dicoCleVar,true, false);
        //À changer livrable 4
        }
        catch (NumberFormatException a){
            ErreurFenetre erreur = new ErreurFenetre();
            erreur.setMsg("Caractère non numerique ou vide");
            erreur.setVisible(true);
            erreur.setBounds(1500, 720, 300, 200);
        };
    }//GEN-LAST:event_sauvegarderAccessoireActionPerformed

    private void effacerAccessoire1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_effacerAccessoire1ActionPerformed
        Controleur.supprimerAccessoire(Integer.parseInt(dicoCle.getText()));
        getParent().remove(this);
    }//GEN-LAST:event_effacerAccessoire1ActionPerformed

    private void positionXPiEntreeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_positionXPiEntreeKeyTyped
        if (buffer != positionXPiEntree.getText())
        {
        indicateurModification.setForeground(Color.blue);
        indicateurModification.setText("Modifié");
        }
        else 
        {
        indicateurModification.setForeground(Color.green);
        indicateurModification.setText("Sauvegardé");
        }
    }//GEN-LAST:event_positionXPiEntreeKeyTyped

    private void positionXPiEntreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_positionXPiEntreeMouseClicked
        buffer = positionXPiEntree.getText();
    }//GEN-LAST:event_positionXPiEntreeMouseClicked

    private void positionXPoEntreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_positionXPoEntreeMouseClicked
        buffer = positionXPoEntree.getText();
    }//GEN-LAST:event_positionXPoEntreeMouseClicked

    private void positionXPoEntreeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_positionXPoEntreeKeyTyped
        if (buffer != positionXPoEntree.getText())
        {
        indicateurModification.setForeground(Color.blue);
        indicateurModification.setText("Modifié");
        }
        else 
        {
        indicateurModification.setForeground(Color.green);
        indicateurModification.setText("Sauvegardé");
        }
    }//GEN-LAST:event_positionXPoEntreeKeyTyped

    private void hauteurPiEntreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hauteurPiEntreeMouseClicked
        System.out.print(buffer);
        buffer = hauteurPiEntree.getText();
    }//GEN-LAST:event_hauteurPiEntreeMouseClicked

    private void hauteurPiEntreeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hauteurPiEntreeKeyTyped
        System.out.print(buffer);
        if (buffer != hauteurPiEntree.getText())
        {
        indicateurModification.setForeground(Color.blue);
        indicateurModification.setText("Modifié");
        }
        else 
        {
        indicateurModification.setForeground(Color.green);
        indicateurModification.setText("Sauvegardé");
        }
    }//GEN-LAST:event_hauteurPiEntreeKeyTyped

    private void hauteurPoEntreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hauteurPoEntreeMouseClicked
        buffer = hauteurPoEntree.getText();
    }//GEN-LAST:event_hauteurPoEntreeMouseClicked

    private void hauteurPoEntreeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hauteurPoEntreeKeyTyped
        if (buffer != hauteurPoEntree.getText())
        {
        indicateurModification.setForeground(Color.blue);
        indicateurModification.setText("Modifié");
        }
        else 
        {
        indicateurModification.setForeground(Color.green);
        indicateurModification.setText("Sauvegardé");
        }
    }//GEN-LAST:event_hauteurPoEntreeKeyTyped

    private void largeurPiEntreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_largeurPiEntreeMouseClicked
        buffer = largeurPiEntree.getText();
    }//GEN-LAST:event_largeurPiEntreeMouseClicked

    private void largeurPiEntreeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_largeurPiEntreeKeyTyped
        if (buffer != largeurPiEntree.getText())
        {
        indicateurModification.setForeground(Color.blue);
        indicateurModification.setText("Modifié");
        }
        else 
        {
        indicateurModification.setForeground(Color.green);
        indicateurModification.setText("Sauvegardé");
        }
    }//GEN-LAST:event_largeurPiEntreeKeyTyped

    private void largeurPoEntreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_largeurPoEntreeMouseClicked
        buffer = largeurPoEntree.getText();
    }//GEN-LAST:event_largeurPoEntreeMouseClicked

    private void largeurPoEntreeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_largeurPoEntreeKeyTyped
        if (buffer != largeurPoEntree.getText())
        {
        indicateurModification.setForeground(Color.blue);
        indicateurModification.setText("Modifié");
        }
        else 
        {
        indicateurModification.setForeground(Color.green);
        indicateurModification.setText("Sauvegardé");
        }
    }//GEN-LAST:event_largeurPoEntreeKeyTyped

    private void positionXPiEntreeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_positionXPiEntreeMouseExited
        if (buffer == positionXPiEntree.getText())
        {
        System.out.print("hellobuffer");
        indicateurModification.setForeground(Color.green);
        indicateurModification.setText("Sauvegardé");
        }
        
    }//GEN-LAST:event_positionXPiEntreeMouseExited
    
    public void initialisation (float[] posX, float[] hauteur, float[] largeur, int cle, Controleur ControleurArg){
        //On utilise des array pour alleger la definition et le nombre de variables
        //On initialise tout les champs aux valeurs passées dans la case de création
        positionXPiEntree.setText(String.valueOf(posX[0]));
        positionXPoEntree.setText(String.valueOf(posX[1]));
        positionXPoNum.setText(String.valueOf(posX[2]));
        positionXPoDen.setText(String.valueOf(posX[3]));
        hauteurPiEntree.setText(String.valueOf(hauteur[0]));
        hauteurPoEntree.setText(String.valueOf(hauteur[1]));
        hauteurPoNum.setText(String.valueOf(hauteur[2]));
        hauteurPoDen.setText(String.valueOf(hauteur[3]));
        largeurPiEntree.setText(String.valueOf(largeur[0]));
        largeurPoEntree.setText(String.valueOf(largeur[1]));
        largeurPoNum.setText(String.valueOf(largeur[2]));
        largeurPoDen.setText(String.valueOf(largeur[3]));
        dicoCle.setText(String.valueOf(cle));
        Controleur = ControleurArg;
        indicateurModification.setForeground(Color.green);
        indicateurModification.setText("Sauvegardé");
    }

    private Controleur Controleur;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PositionX;
    private javax.swing.JLabel dicoCle;
    private javax.swing.JButton effacerAccessoire1;
    private javax.swing.JTextField hauteurPiEntree;
    private javax.swing.JTextField hauteurPoDen;
    private javax.swing.JTextField hauteurPoEntree;
    private javax.swing.JTextField hauteurPoNum;
    private javax.swing.JLabel indicateurModification;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField largeurPiEntree;
    private javax.swing.JTextField largeurPoDen;
    private javax.swing.JTextField largeurPoEntree;
    private javax.swing.JTextField largeurPoNum;
    private javax.swing.JLabel longueurAvantDivision;
    private javax.swing.JLabel longueurAvantDivision1;
    private javax.swing.JLabel longueurAvantDivision2;
    private javax.swing.JLabel longueurAvantFtLabel1;
    private javax.swing.JLabel longueurAvantFtLabel2;
    private javax.swing.JLabel longueurAvantInLabel;
    private javax.swing.JLabel longueurAvantInLabel1;
    private javax.swing.JLabel longueurAvantInLabel2;
    private javax.swing.JLabel longueurAvantLabel1;
    private javax.swing.JLabel longueurAvantLabel2;
    private javax.swing.JLabel positionXFtLabel;
    private javax.swing.JTextField positionXPiEntree;
    private javax.swing.JTextField positionXPoDen;
    private javax.swing.JTextField positionXPoEntree;
    private javax.swing.JTextField positionXPoNum;
    private javax.swing.JButton sauvegarderAccessoire;
    private javax.swing.JLabel vieuxValX;
    private javax.swing.JLabel vieuxValY;
    // End of variables declaration//GEN-END:variables
    private String buffer;
}
